input {
    beats {
        port => 5044
    }
}

filter {
    if [service] == "recipegen" and [component] == "backend" {
        mutate {
            rename => { "name" => "file" }
        }
    }

    # dynamically populate data_stream metadata so we can route logs
    mutate {
        # static type, always logs
        replace => { "[data_stream][type]" => "logs" }

        # dataset constructed from service and component; no placeholders
        # put a separator (dot or underscore) if you like, avoid spaces
        replace => { "[data_stream][dataset]" => "%{service}.%{component}" }

        # namespace corresponds to environment field
        replace => { "[data_stream][namespace]" => "%{environment}" }
    }
}

output {
    if [service] == "recipegen" {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            user => "logstash_writer_recipeGen"
            password => "${LOGSTASH_WRITER_RECIPEGEN_PASSWORD}"
            ecs_compatibility => "v8"

            # rely on [data_stream] event metadata populated in the filter section
            data_stream => true
        }
        stdout { codec => rubydebug}
    }
    # # Uncomment below to debug: see events in Logstash stdout (docker logs logstash)
    # else {
    #   stdout { codec => rubydebug { metadata => true } }
    # }
}